var LOTRApp = angular.module('LOTRApp', []);

LOTRApp.controller('LOTRController', function($scope) {
  $scope.character = '';
  $scope.selectedCharacter = '';
  $scope.characters = [
    {name: 'Aragorn', fullname:"Aragorn II, son of Arathorn", image: 'images/aragorn.jpg', bio:"Aragorn led the Fellowship of the Ring following the loss of Gandalf in the Mines of Moria while fighting the Balrog. When the Fellowship was broken, he tracked the hobbits Meriadoc Brandybuck and Peregrin Took with the help of Legolas the elf and Gimli the dwarf to Fangorn Forest. He then fought in the battle at Helm's Deep and the Battle of the Pelennor Fields. After defeating Sauron's forces in Gondor, he led an army of Gondor and Rohan against the Black Gate of Mordor to distract Sauron's attention so that Frodo Baggins and Samwise Gamgee could have a chance to destroy the One Ring."},
    {name: 'Arwen', fullname: "Arwen Undomiel", image: 'images/arwen.jpg', bio:"Arwen was the youngest child of Elrond and Celebrían. Her elder brothers were the twins Elladan and Elrohir. Her name, Ar-wen, means 'noble maiden'. She bore the sobriquet 'Evenstar' (or Evening Star), as the most beautiful of the last generation of High Elves in Middle-earth."},
    {name: 'Bilbo', fullname: "Bilbo Baggins", image: 'images/bilbo.jpg', bio:"Bilbo Baggins, a hobbit in comfortable middle age, was hired as a 'burglar' –despite his initial objections– by the wizard Gandalf and 13 Dwarves led by their king, Thorin Oakenshield. The Dwarves were on a quest to reclaim the Lonely Mountain and its treasures from the dragon Smaug. The adventure took Bilbo and his companions through the wilderness, to the elf haven of Rivendell, across the Misty Mountains, through the black forest of Mirkwood, to Lake-town in the middle of Long Lake, and eventually to the Mountain itself"},
    {name: 'Elrond', fullname: "Elrond Half-elven", image: 'images/elrond.jpg', bio: "Elrond was Lord of Rivendell, one of the elven leaders that remained in Middle-earth in its Third Age. His name was explained by Tolkien in a letter from 1958 to Rhona Beare as 'Elf of the Cave', as he was found as an infant abandoned in a cave. Later notes, reflected in The Silmarillion and The War of the Jewels, interpret the name instead as 'Star-dome' or 'Vault of Stars' (a vault in the sense of the celestial dome)."},
    {name: 'Frodo', fullname: "Frodo Baggins", image: 'images/frodo.jpg', bio:"Frodo came of age (at 33 years old) and Bilbo left the Shire for good on his one hundred and eleventh birthday. Frodo inherited Bag End and Bilbo's ring, which were both introduced in The Hobbit. Gandalf, at this time, was not certain about the origin of the Ring, so he warned Frodo to avoid using it and to keep it secret. Frodo kept the Ring hidden for 17 years, resulting in it giving him the same longevity of Bilbo, until Gandalf returned to tell him that it was the One Ring of the Dark Lord Sauron, who desired to use it to conquer Middle-earth."},
    {name: 'Galadriel', fullname: "Galadriel", image: 'images/galadriel.jpg', bio:"She was a royal Elf of both the Noldor and the Teleri, being a grandchild of both King Finwe and King Olwe, and was also close kin of King Ingwe of the Vanyar through her grandmother Indis. She was one of the leaders in the rebellion of the Noldor and their flight from Valinor during the First Age, and she was the only prominent Noldo to survive and eventually return, at the end of the Third Age."},
    {name: 'Gandalf', fullname: "Gandalf the Grey", image: 'images/gandalf.jpg', bio:"The Istari arrived in Middle-earth separately, around T.A. 1000; Gandalf the Grey was the last, landing in the Havens of Mithlond. He seemed the oldest and least in stature of them, but Círdan the Shipwright felt that he had the highest inner greatness on their first meeting in the Havens, and gave him Narya, the Ring of Fire. Saruman, the chief Wizard, later learned of the gift and resented it. Gandalf hid the ring well, and it was not widely known until he left with the other ring-bearers at the end of the Third Age that he, and not Círdan, was the holder of the third of the Elven-rings."},
    {name: 'Gimli', fullname: "Gimli son of Gloin", image: 'images/gimli.jpg', bio:"Gimli was born in the Ered Luin (Blue Mountains) in the year 2879 of the Third Age. His father was Gloin, one of the former companions of the hobbit, Bilbo Baggins. Gimli had wanted to accompany his father and the others in the company of Thorin Oakenshield on their quest to reclaim Erebor (the Lonely Mountain) in the year 2941, but at age 62 he was deemed too young."},
    {name: 'Gollum', fullname: "Smeagol", image: 'images/gollum.jpg', bio: "A small, slimy creature who lived on a small island in the centre of an underground lake at the roots of the Misty Mountains. He survived on cave fish, which he caught from his small boat, and small goblins who strayed too far from the stronghold of the Great Goblin. Over the years, his eyes adapted to the dark and became 'lamp-like', shining with a sickly pale light."},
    {name: 'Legolas', fullname: "Legolas son of Thranduil", image: 'images/legolas.jpg', bio:"Legolas was the son of Thranduil, King of the Woodland Realm of Northern Mirkwood, who appears as 'the Elvenking' in The Hobbit. Thranduil ruled over the Silvan Elves or 'Wood-elves' of Mirkwood. Although he lived among the Silvan Elves, Legolas was not one himself. His father Thranduil had originally come from Lindon; he and his son were actually Sindar, or 'Grey Elves', called in the singular Sinda; 'Sindarin' was their language. Thranduil himself was the son of Oropher. Legolas's mother is never mentioned; the Elves of Mirkwood have no Queen at the time of The Hobbit."},
    {name: 'Merry', fullname: "Meriadoc Brandybuck", image: 'images/marry.png', bio: "Meriadoc 'Merry' Brandybuck (later known as Meriadoc 'Merry' Brandybuck I, due to his grandson's birth) was a Hobbit and one of Frodo's cousins and closest friends. He loved boats and ponies and had a great interest in the maps of Middle-earth. He was also one of the nine companions of the Fellowship of the Ring, and later became the eighth Master of Buckland."},
    {name: 'Sam', fullname: "Samwise Gamgee", image: 'images/sam.jpg', bio:"Samwise Gamgee, known as Sam, was a Hobbit of the Shire. He was Frodo Baggins' gardener and best friend. Sam proved himself to be Frodo's closest and most dependable companion, the most loyal of the Fellowship of the Ring, and also played a critical role in protecting Frodo and destroying the One Ring."},
    {name: 'Saruman', fullname: "Saruman the White", image: 'images/saruman.jpg', bio: "Saruman (Quenya; IPA: ['saruman] - 'Man Of Skill'), also known as Saruman the White and Sharkey was an Istar (wizard), who lived in Middle-earth during the Third Age. Originally, he was the chief of the wizards and of the White Council that opposed Sauron. His extensive studies of dark magic, however, eventually led him to desire the One Ring for himself. Thinking he could ally himself with Sauron and then betray him, Saruman allied Isengard with Mordor in the War of the Ring, in which he was defeated."},
    {name: 'Sauron', fullname: "Sauron", image: 'images/sauron.jpg', bio:"Sauron (or Þauron (Thauron); Quenya; IPA: [ˈsaʊron] or Vanyarin; IPA: [ˈθaʊron] - 'The Abhorred'), the eponymous Lord of the Rings, was a fallen Maia, the creator of the One Ring, and the most trusted lieutenant of his master Melkor (Morgoth, the first Dark Lord). After Melkor's defeat in the First Age, Sauron became the second Dark Lord and strove to conquer Arda by creating the Rings of Power. In the Second Age, he was defeated in the War of the Last Alliance by the last line of defense: Elves and Men under kings Gil-galad and Elendil."},
    {name: 'Smeagol', fullname: "Smeagol", image: 'images/smeagull.jpg', bio: "A small, slimy creature who lived on a small island in the centre of an underground lake at the roots of the Misty Mountains. He survived on cave fish, which he caught from his small boat, and small goblins who strayed too far from the stronghold of the Great Goblin. Over the years, his eyes adapted to the dark and became 'lamp-like', shining with a sickly pale light."},
    {name: 'Treebeard', fullname:"Treebeard", image: 'images/treebeard.jpg', bio:"Treebeard, also known as Fangorn, was the oldest of the Ents left in Middle-earth, an ancient tree-like being who is a 'shepherd of trees'. He had a very tall and stiff-limbed appearance, with bark-like skin and leafy hair."},
  ];

});
